// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.12.4
// source: protos/classification.proto

package music_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Genres int32

const (
	Genres_UNKNOWN   Genres = 0
	Genres_blues     Genres = 1
	Genres_classical Genres = 2
	Genres_country   Genres = 3
	Genres_disco     Genres = 4
	Genres_hiphop    Genres = 5
	Genres_jazz      Genres = 6
	Genres_metal     Genres = 7
	Genres_pop       Genres = 8
	Genres_reggae    Genres = 9
	Genres_rock      Genres = 10
)

// Enum value maps for Genres.
var (
	Genres_name = map[int32]string{
		0:  "UNKNOWN",
		1:  "blues",
		2:  "classical",
		3:  "country",
		4:  "disco",
		5:  "hiphop",
		6:  "jazz",
		7:  "metal",
		8:  "pop",
		9:  "reggae",
		10: "rock",
	}
	Genres_value = map[string]int32{
		"UNKNOWN":   0,
		"blues":     1,
		"classical": 2,
		"country":   3,
		"disco":     4,
		"hiphop":    5,
		"jazz":      6,
		"metal":     7,
		"pop":       8,
		"reggae":    9,
		"rock":      10,
	}
)

func (x Genres) Enum() *Genres {
	p := new(Genres)
	*p = x
	return p
}

func (x Genres) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Genres) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_classification_proto_enumTypes[0].Descriptor()
}

func (Genres) Type() protoreflect.EnumType {
	return &file_protos_classification_proto_enumTypes[0]
}

func (x Genres) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Genres.Descriptor instead.
func (Genres) EnumDescriptor() ([]byte, []int) {
	return file_protos_classification_proto_rawDescGZIP(), []int{0}
}

type UploadAudioRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	FileData      []byte                 `protobuf:"bytes,2,opt,name=file_data,json=fileData,proto3" json:"file_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadAudioRequest) Reset() {
	*x = UploadAudioRequest{}
	mi := &file_protos_classification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadAudioRequest) ProtoMessage() {}

func (x *UploadAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_classification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadAudioRequest.ProtoReflect.Descriptor instead.
func (*UploadAudioRequest) Descriptor() ([]byte, []int) {
	return file_protos_classification_proto_rawDescGZIP(), []int{0}
}

func (x *UploadAudioRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadAudioRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

type Genre struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Genre         Genres                 `protobuf:"varint,1,opt,name=genre,proto3,enum=classification.Genres" json:"genre,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Genre) Reset() {
	*x = Genre{}
	mi := &file_protos_classification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Genre) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Genre) ProtoMessage() {}

func (x *Genre) ProtoReflect() protoreflect.Message {
	mi := &file_protos_classification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Genre.ProtoReflect.Descriptor instead.
func (*Genre) Descriptor() ([]byte, []int) {
	return file_protos_classification_proto_rawDescGZIP(), []int{1}
}

func (x *Genre) GetGenre() Genres {
	if x != nil {
		return x.Genre
	}
	return Genres_UNKNOWN
}

var File_protos_classification_proto protoreflect.FileDescriptor

var file_protos_classification_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63,
	0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x4d, 0x0a,
	0x12, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x75, 0x64, 0x69, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x61, 0x74, 0x61, 0x22, 0x35, 0x0a, 0x05,
	0x47, 0x65, 0x6e, 0x72, 0x65, 0x12, 0x2c, 0x0a, 0x05, 0x67, 0x65, 0x6e, 0x72, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x52, 0x05, 0x67, 0x65,
	0x6e, 0x72, 0x65, 0x2a, 0x87, 0x01, 0x0a, 0x06, 0x47, 0x65, 0x6e, 0x72, 0x65, 0x73, 0x12, 0x0b,
	0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x62,
	0x6c, 0x75, 0x65, 0x73, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69,
	0x63, 0x61, 0x6c, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79,
	0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x10, 0x04, 0x12, 0x0a, 0x0a,
	0x06, 0x68, 0x69, 0x70, 0x68, 0x6f, 0x70, 0x10, 0x05, 0x12, 0x08, 0x0a, 0x04, 0x6a, 0x61, 0x7a,
	0x7a, 0x10, 0x06, 0x12, 0x09, 0x0a, 0x05, 0x6d, 0x65, 0x74, 0x61, 0x6c, 0x10, 0x07, 0x12, 0x07,
	0x0a, 0x03, 0x70, 0x6f, 0x70, 0x10, 0x08, 0x12, 0x0a, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x67, 0x61,
	0x65, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x72, 0x6f, 0x63, 0x6b, 0x10, 0x0a, 0x32, 0x61, 0x0a,
	0x15, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0b, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x41, 0x75, 0x64, 0x69, 0x6f, 0x12, 0x22, 0x2e, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x41, 0x75, 0x64,
	0x69, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x6c, 0x61, 0x73,
	0x73, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x47, 0x65, 0x6e, 0x72, 0x65,
	0x42, 0x10, 0x5a, 0x0e, 0x2f, 0x6d, 0x75, 0x73, 0x69, 0x63, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_classification_proto_rawDescOnce sync.Once
	file_protos_classification_proto_rawDescData = file_protos_classification_proto_rawDesc
)

func file_protos_classification_proto_rawDescGZIP() []byte {
	file_protos_classification_proto_rawDescOnce.Do(func() {
		file_protos_classification_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_classification_proto_rawDescData)
	})
	return file_protos_classification_proto_rawDescData
}

var file_protos_classification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_classification_proto_goTypes = []any{
	(Genres)(0),                // 0: classification.Genres
	(*UploadAudioRequest)(nil), // 1: classification.UploadAudioRequest
	(*Genre)(nil),              // 2: classification.Genre
}
var file_protos_classification_proto_depIdxs = []int32{
	0, // 0: classification.Genre.genre:type_name -> classification.Genres
	1, // 1: classification.ClassificationService.UploadAudio:input_type -> classification.UploadAudioRequest
	2, // 2: classification.ClassificationService.UploadAudio:output_type -> classification.Genre
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_classification_proto_init() }
func file_protos_classification_proto_init() {
	if File_protos_classification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_classification_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_classification_proto_goTypes,
		DependencyIndexes: file_protos_classification_proto_depIdxs,
		EnumInfos:         file_protos_classification_proto_enumTypes,
		MessageInfos:      file_protos_classification_proto_msgTypes,
	}.Build()
	File_protos_classification_proto = out.File
	file_protos_classification_proto_rawDesc = nil
	file_protos_classification_proto_goTypes = nil
	file_protos_classification_proto_depIdxs = nil
}
