# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/classification.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/classification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bprotos/classification.proto\x12\x0e\x63lassification\"9\n\x12UploadAudioRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x11\n\tfile_data\x18\x02 \x01(\x0c\".\n\x05Genre\x12%\n\x05genre\x18\x01 \x01(\x0e\x32\x16.classification.Genres*\x87\x01\n\x06Genres\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05\x62lues\x10\x01\x12\r\n\tclassical\x10\x02\x12\x0b\n\x07\x63ountry\x10\x03\x12\t\n\x05\x64isco\x10\x04\x12\n\n\x06hiphop\x10\x05\x12\x08\n\x04jazz\x10\x06\x12\t\n\x05metal\x10\x07\x12\x07\n\x03pop\x10\x08\x12\n\n\x06reggae\x10\t\x12\x08\n\x04rock\x10\n2a\n\x15\x43lassificationService\x12H\n\x0bUploadAudio\x12\".classification.UploadAudioRequest\x1a\x15.classification.Genreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.classification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENRES']._serialized_start=155
  _globals['_GENRES']._serialized_end=290
  _globals['_UPLOADAUDIOREQUEST']._serialized_start=47
  _globals['_UPLOADAUDIOREQUEST']._serialized_end=104
  _globals['_GENRE']._serialized_start=106
  _globals['_GENRE']._serialized_end=152
  _globals['_CLASSIFICATIONSERVICE']._serialized_start=292
  _globals['_CLASSIFICATIONSERVICE']._serialized_end=389
# @@protoc_insertion_point(module_scope)
